name: onesma_player2
description: A minimal application for demonstrating & testing package:media_kit
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video
  media_kit_native_event_loop:
    path: ../media_kit_native_event_loop
  media_kit_libs_windows_video:
    path: ../media_kit_libs_windows_video
  media_kit_libs_linux:
    path: ../media_kit_libs_linux
  media_kit_libs_macos_video:
    path: ../media_kit_libs_macos_video
  media_kit_libs_ios_video:
    path: ../media_kit_libs_ios_video
  media_kit_libs_android_video:
    path: ../media_kit_libs_android_video
 

  path: ^1.8.2
  http: ^0.13.5
  file_picker: ^5.3.3
  path_provider: ^2.0.14
  window_manager: ^0.3.8
  font_awesome_flutter: ^10.6.0
  flutter_launcher_icons: ^0.13.1
  xml: ^6.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"


dependency_overrides:
  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video
  media_kit_native_event_loop:
    path: ../media_kit_native_event_loop
  media_kit_libs_windows_video:
    path: ../media_kit_libs_windows_video
  media_kit_libs_linux:
    path: ../media_kit_libs_linux
  media_kit_libs_macos_video:
    path: ../media_kit_libs_macos_video
  media_kit_libs_ios_video:
    path: ../media_kit_libs_ios_video
  media_kit_libs_android_video:
    path: ../media_kit_libs_android_video

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
